# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
